name: NodeJS CI workflow for libraries
on:
  workflow_call:
    inputs:
      runMutationTests:
        description: 'Defines if mutation tests should be run'
        default: false
        required: false
        type: boolean

jobs:
  nodejscilibs:
    name: NodeJS-CI-libs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x, 22.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Check for linting issues
        run: npm run lint
      - name: Check for formatting issues
        run: npm run checkformat  
      - name: Run tests
        run: npm test
      - name: Check types
        run: npm run check
      - name: Run mutation tests
        if: ${{ inputs.runMutationTests }}
        run: npm run mutationtestCI
