name: NodeJS CI workflow
on:
  workflow_call:
    inputs:
      only-latest-lts:
        default: false
        required: false
        type: boolean

jobs:
  nodejsci:
    name: NodeJS-CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - version: '18.x'
            if: ${{ inputs.only-latest-lts == false }}
          - version: '20.x'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version.version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version.version }}
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Check for linting issues
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Check types
        run: npm run check
